    [build]
      publish = "."  # Publish the root directory directly
      command = "# No build command needed for this simple HTML/JS POC"

    [functions]
      directory = "netlify/functions"
      node_bundler = "esbuild"

    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
    
