[build]
  publish = "."
  command = "echo 'Deploying MBS GOAT static site'"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  node_version = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
