[build]
  base = "."
  publish = "."
  command = "echo 'Deploying static site'"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
