[build]
  base = "."
  publish = "."
  command = "echo 'Deploying static site'"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
