[build]
  publish = "public"          # or "dist" or wherever your HTML lives
  command = "echo 'No build needed'"  # or "npm run build" if using one

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"         # ✅ Correct place to specify Node version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
