[build]
  base = "."
  publish = "."
  command = "echo 'Deploying static site'"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect /success to /success.html
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Redirect /cancel to /cancel.html
[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200

# Catch-all redirect (keep this one last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
